setup_remote_docker: &setup_remote_docker
  version: 18.06.0-ce
  reusable: true
  exclusive: true
  docker_layer_caching: true

docker_login: &docker_login
  name: docker login
  command: |
    docker login -u _json_key -p "$GCLOUD_SERVICE_KEY" https://gcr.io

init_gcloud: &init_gcloud
  name: Init gcloud
  command: .circleci/init-gcloud.sh

run_consul: &run_rtmp_runner
  name: run rtmp runner
  command: |
    make docker-run
  background: true
  working_directory: /srv/src/rtmp_runner

base_docker_image: &base_docker_image
  - image: gcr.io/videocoin-network/cloud-base-ci:1.0
    auth:
      username: _json_key
      password: $GCLOUD_SERVICE_KEY

restore_repo: &restore_repo
  restore_cache:
    keys:
      - v1-repo-{{ .Branch }}-{{ .Revision }}
      - v1-repo-{{ .Branch }}
      - v1-repo

defaults: &defaults
  working_directory: /srv/src
  docker: *base_docker_image

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - *restore_repo
      - checkout
      - setup_remote_docker:
          <<: *setup_remote_docker
      - run:
          <<: *docker_login
      - run:
          name: build rtmp runner
          command: |
            make docker-build
          working_directory: /srv/src/rtmp_runner
      - run:
          <<: *run_rtmp_runner
      - run:
          name:  build test image
          command: |
            make docker-build
      - run:
          name: test
          command: |
            make docker-run
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: develop
    jobs:
      - test
  build-n-deploy:
    jobs:
      - test
